# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'odango UIKit' do
  # Comment the next line if you've re not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'FSCalendar'


  # Pods for odango UIKit


end
