# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'odango UIKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for odango UIKit


pod 'FSCalendar'

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
pod 'Firebase/Storage'
pod 'Nuke'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods


end
